name: Continuous builds

on:
  push:
    branches:
      - main
      - development
      - experimental
      - 'test*'
  pull_request:
    branches:
      - main
      - development
      - experimental
      - 'test*'

jobs:
  build:
    env:
      UV_SYSTEM_PYTHON: 1

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
      fail-fast: false

    steps:

    - uses: actions/checkout@v4
    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version:  ${{ matrix.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Print refs
      run: |
        echo "github.ref is: ${{ github.ref }}"
        echo "github.base_ref is: ${{ github.base_ref }}"


    - name: Install package
      run: |
        uv pip install -r ./requirements.txt

    - name: List packages so far
      run: |
        uv pip list
        env

    - name: Run simple test
      run: |
        nml-ai --help

    - name: Setup Ollama
      uses: ai-action/setup-ollama@v1

    - name: Pull default models
      run: |
        ollama pull qwen3:0.6b
        ollama pull bge-m3

    - name: Run unit tests
      run: |
        pushd rag_pkg && pytest -v && popd
      env:
        NML_AI_VS_CONFIG: "vector-stores-tests.json"

    - name: Lint with ruff
      run: |
        ruff check . --exit-zero
